# generated by puppet
rhizomatica_dir = '/var/rhizomatica'
sq_hlr_path = '/var/lib/osmocom/hlr.sqlite3'
kannel_password = 'Nan3RZhekZy0'
pgsql_db = 'rhizomatica'
pgsql_user = 'rhizomatica'
pgsql_pwd = 'xEP3Y4W8gG*4*zu'
pgsql_host = 'localhost
